### ISSUE TITLE
Number of wallets giving error 500 on /dev/tz

### ISSUE THREAD

**Issue by tgreiser** [hicetnunc2000/hicetnunc-api#69]
Some wallets work. Others give this error.

```{	"tz": "tz1ceVPzbPAWja66PQk7QCL5kd212jnrhLDM" }```

```Error: Request failed with status code 500
    at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)```

**Comment by skenaja** [comment]
More examples:
https://github.com/hicetnunc2000/hicetnunc/issues/681
https://github.com/hicetnunc2000/hicetnunc/issues/683

Main issue seems to be [scanning object owners for burned items](https://github.com/hicetnunc2000/hicetnunc-api/blob/master/lib/router/readIssuer.js#L60), especially when there are more than 200 objkts - this seems to be the point where rate limiting kicks in by BCD here: [getObjktOwners](https://github.com/hicetnunc2000/hicetnunc-api/blob/master/lib/utils.js#L142)
