### ISSUE TITLE
Npm start crash

### ISSUE THREAD

**Issue by slothdude** [hicetnunc2000/hicetnunc-api#74]
Hi, I am trying to run `npm start` and am getting this error:

```
(node:17644) ExperimentalWarning: The fs.promises API is experimental
(node:17644) ExperimentalWarning: The dns.promises API is experimental
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES

 Serverless Error ----------------------------------------

  The Serverless version (2.35.0) does not satisfy the "frameworkVersion" (2.8.0) in serverless.yml

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              10.16.0
     Framework Version:         2.35.0
     Plugin Version:            4.6.0
     SDK Version:               4.2.2
     Components Version:        3.9.2
     
```
I thought it may be because of the node gyp error I got:
When running ` npm install -g serverless@2.35.0` l I got this node-gyp error:

```
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Users\sloth\AppData\Local\Microsoft\WindowsApps", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (H:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (H:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at H:\ProgramFiles\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "H:\\ProgramFiles\\nodejs\\node.exe" "H:\\ProgramFiles\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\sloth\AppData\Roaming\npm\node_modules\serverless\node_modules\snappy
gyp ERR! node -v v10.16.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
```

and tried setting the PYTHON env variable to the folder where my python.exe is located but this step still fails. Any other ideas for things I could try?

**Comment by skenaja** [comment]
`Node Version:              10.16.0`

This is below the recommended version in the package.json

This is what I have running (on Windows, but via WSL2 Ubuntu 20.04 rather than directly in Win10)

```
alex@LAPTOP-O0B0BFUC:~/hicetnunc-api$ node -v
v12.20.1
alex@LAPTOP-O0B0BFUC:~/hicetnunc-api$ npm -v
6.14.10
alex@LAPTOP-O0B0BFUC:~/hicetnunc-api$ serverless -v
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: DOTENV: Loading environment variables from .env:
Serverless:      - TIMESTAMP
Serverless:      - BUFFER
Framework Core: 2.8.0 (local)
Plugin: 4.6.0
SDK: n/a
Components: 3.9.2
